// 多语言国家列表 - 以 code 作为唯一标识
export interface CountryData {
  code: string;
  name: {
    'zh-CN': string;
    'en-US': string;
    'fr-FR': string;
  };
}

export const COUNTRY_LIST: CountryData[] = [
  {"code": "AF", "name": {"zh-CN": "阿富汗", "en-US": "Afghanistan", "fr-FR": "Afghanistan"}},
  {"code": "AL", "name": {"zh-CN": "阿尔巴尼亚", "en-US": "Albania", "fr-FR": "Albanie"}},
  {"code": "DZ", "name": {"zh-CN": "阿尔及利亚", "en-US": "Algeria", "fr-FR": "Algérie"}},
  {"code": "AS", "name": {"zh-CN": "美属萨摩亚", "en-US": "American Samoa", "fr-FR": "Samoa américaines"}},
  {"code": "AD", "name": {"zh-CN": "安道尔", "en-US": "Andorra", "fr-FR": "Andorre"}},
  {"code": "AO", "name": {"zh-CN": "安哥拉", "en-US": "Angola", "fr-FR": "Angola"}},
  {"code": "AI", "name": {"zh-CN": "安圭拉", "en-US": "Anguilla", "fr-FR": "Anguilla"}},
  {"code": "AQ", "name": {"zh-CN": "南极洲", "en-US": "Antarctica", "fr-FR": "Antarctique"}},
  {"code": "AG", "name": {"zh-CN": "安提瓜和巴布达", "en-US": "Antigua and Barbuda", "fr-FR": "Antigua-et-Barbuda"}},
  {"code": "AR", "name": {"zh-CN": "阿根廷", "en-US": "Argentina", "fr-FR": "Argentine"}},
  {"code": "AM", "name": {"zh-CN": "亚美尼亚", "en-US": "Armenia", "fr-FR": "Arménie"}},
  {"code": "AW", "name": {"zh-CN": "阿鲁巴", "en-US": "Aruba", "fr-FR": "Aruba"}},
  {"code": "AU", "name": {"zh-CN": "澳大利亚", "en-US": "Australia", "fr-FR": "Australie"}},
  {"code": "AT", "name": {"zh-CN": "奥地利", "en-US": "Austria", "fr-FR": "Autriche"}},
  {"code": "AZ", "name": {"zh-CN": "阿塞拜疆", "en-US": "Azerbaijan", "fr-FR": "Azerbaïdjan"}},
  {"code": "BS", "name": {"zh-CN": "巴哈马", "en-US": "Bahamas", "fr-FR": "Bahamas"}},
  {"code": "BH", "name": {"zh-CN": "巴林", "en-US": "Bahrain", "fr-FR": "Bahreïn"}},
  {"code": "BD", "name": {"zh-CN": "孟加拉", "en-US": "Bangladesh", "fr-FR": "Bangladesh"}},
  {"code": "BB", "name": {"zh-CN": "巴巴多斯", "en-US": "Barbados", "fr-FR": "Barbade"}},
  {"code": "BY", "name": {"zh-CN": "白俄罗斯", "en-US": "Belarus", "fr-FR": "Biélorussie"}},
  {"code": "BE", "name": {"zh-CN": "比利时", "en-US": "Belgium", "fr-FR": "Belgique"}},
  {"code": "BZ", "name": {"zh-CN": "贝里斯", "en-US": "Belize", "fr-FR": "Belize"}},
  {"code": "BJ", "name": {"zh-CN": "贝宁", "en-US": "Benin", "fr-FR": "Bénin"}},
  {"code": "BM", "name": {"zh-CN": "百慕大", "en-US": "Bermuda", "fr-FR": "Bermudes"}},
  {"code": "BT", "name": {"zh-CN": "不丹", "en-US": "Bhutan", "fr-FR": "Bhoutan"}},
  {"code": "BO", "name": {"zh-CN": "玻利维亚", "en-US": "Bolivia", "fr-FR": "Bolivie"}},
  {
    "code": "BA",
    "name": {"zh-CN": "波斯尼亚和黑塞哥维那", "en-US": "Bosnia and Herzegovina", "fr-FR": "Bosnie-Herzégovine"}
  },
  {"code": "BW", "name": {"zh-CN": "博茨瓦纳", "en-US": "Botswana", "fr-FR": "Botswana"}},
  {"code": "BV", "name": {"zh-CN": "波维特岛", "en-US": "Bouvet Island", "fr-FR": "Île Bouvet"}},
  {"code": "BR", "name": {"zh-CN": "巴西", "en-US": "Brazil", "fr-FR": "Brésil"}},
  {
    "code": "IO",
    "name": {
      "zh-CN": "英属印度洋",
      "en-US": "British Indian Ocean Territory",
      "fr-FR": "Territoire britannique de l'océan Indien"
    }
  },
  {"code": "BN", "name": {"zh-CN": "文莱", "en-US": "Brunei", "fr-FR": "Brunéi"}},
  {"code": "BG", "name": {"zh-CN": "保加利亚", "en-US": "Bulgaria", "fr-FR": "Bulgarie"}},
  {"code": "BF", "name": {"zh-CN": "布基纳法索", "en-US": "Burkina Faso", "fr-FR": "Burkina Faso"}},
  {"code": "BI", "name": {"zh-CN": "布隆迪", "en-US": "Burundi", "fr-FR": "Burundi"}},
  {"code": "CV", "name": {"zh-CN": "佛得角", "en-US": "Cape Verde", "fr-FR": "Cap-Vert"}},
  {"code": "KH", "name": {"zh-CN": "柬埔寨", "en-US": "Cambodia", "fr-FR": "Cambodge"}},
  {"code": "CM", "name": {"zh-CN": "喀麦隆", "en-US": "Cameroon", "fr-FR": "Cameroun"}},
  {"code": "CA", "name": {"zh-CN": "加拿大", "en-US": "Canada", "fr-FR": "Canada"}},
  {"code": "KY", "name": {"zh-CN": "开曼群岛", "en-US": "Cayman Islands", "fr-FR": "Îles Caïmanes"}},
  {"code": "CF", "name": {"zh-CN": "中非", "en-US": "Central African Republic", "fr-FR": "République centrafricaine"}},
  {"code": "TD", "name": {"zh-CN": "乍得", "en-US": "Chad", "fr-FR": "Tchad"}},
  {"code": "CL", "name": {"zh-CN": "智利", "en-US": "Chile", "fr-FR": "Chili"}},
  {"code": "CN", "name": {"zh-CN": "中国", "en-US": "China", "fr-FR": "Chine"}},
  {"code": "CX", "name": {"zh-CN": "圣诞岛", "en-US": "Christmas Island", "fr-FR": "Île Christmas"}},
  {"code": "CC", "name": {"zh-CN": "科科斯群岛", "en-US": "Cocos Islands", "fr-FR": "Îles Cocos"}},
  {"code": "CO", "name": {"zh-CN": "哥伦比亚", "en-US": "Colombia", "fr-FR": "Colombie"}},
  {"code": "KM", "name": {"zh-CN": "科摩罗伊斯兰", "en-US": "Comoros", "fr-FR": "Comores"}},
  {
    "code": "CD",
    "name": {
      "zh-CN": "刚果民主共和国",
      "en-US": "Democratic Republic of the Congo",
      "fr-FR": "République démocratique du Congo"
    }
  },
  {"code": "CG", "name": {"zh-CN": "刚果", "en-US": "Republic of the Congo", "fr-FR": "République du Congo"}},
  {"code": "CK", "name": {"zh-CN": "库克群岛", "en-US": "Cook Islands", "fr-FR": "Îles Cook"}},
  {"code": "CR", "name": {"zh-CN": "哥斯达黎加", "en-US": "Costa Rica", "fr-FR": "Costa Rica"}},
  {"code": "HR", "name": {"zh-CN": "克罗地亚", "en-US": "Croatia", "fr-FR": "Croatie"}},
  {"code": "CU", "name": {"zh-CN": "古巴", "en-US": "Cuba", "fr-FR": "Cuba"}},
  {"code": "CY", "name": {"zh-CN": "塞浦路斯", "en-US": "Cyprus", "fr-FR": "Chypre"}},
  {"code": "CZ", "name": {"zh-CN": "捷克", "en-US": "Czech Republic", "fr-FR": "République tchèque"}},
  {"code": "CI", "name": {"zh-CN": "科特迪瓦", "en-US": "Ivory Coast", "fr-FR": "Côte d'Ivoire"}},
  {"code": "DK", "name": {"zh-CN": "丹麦", "en-US": "Denmark", "fr-FR": "Danemark"}},
  {"code": "DJ", "name": {"zh-CN": "吉布提", "en-US": "Djibouti", "fr-FR": "Djibouti"}},
  {"code": "DM", "name": {"zh-CN": "多米尼克", "en-US": "Dominica", "fr-FR": "Dominique"}},
  {"code": "DO", "name": {"zh-CN": "多米尼加共和国", "en-US": "Dominican Republic", "fr-FR": "République dominicaine"}},
  {"code": "EC", "name": {"zh-CN": "厄瓜多尔", "en-US": "Ecuador", "fr-FR": "Équateur"}},
  {"code": "EG", "name": {"zh-CN": "埃及", "en-US": "Egypt", "fr-FR": "Égypte"}},
  {"code": "SV", "name": {"zh-CN": "萨尔瓦多", "en-US": "El Salvador", "fr-FR": "El Salvador"}},
  {"code": "GQ", "name": {"zh-CN": "赤道几内亚", "en-US": "Equatorial Guinea", "fr-FR": "Guinée équatoriale"}},
  {"code": "ER", "name": {"zh-CN": "厄立特里亚", "en-US": "Eritrea", "fr-FR": "Érythrée"}},
  {"code": "EE", "name": {"zh-CN": "爱沙尼亚", "en-US": "Estonia", "fr-FR": "Estonie"}},
  {"code": "SZ", "name": {"zh-CN": "斯威士兰", "en-US": "Eswatini", "fr-FR": "Eswatini"}},
  {"code": "ET", "name": {"zh-CN": "埃塞俄比亚", "en-US": "Ethiopia", "fr-FR": "Éthiopie"}},
  {"code": "FK", "name": {"zh-CN": "福克兰群岛", "en-US": "Falkland Islands", "fr-FR": "Îles Malouines"}},
  {"code": "FO", "name": {"zh-CN": "法罗群岛", "en-US": "Faroe Islands", "fr-FR": "Îles Féroé"}},
  {"code": "FJ", "name": {"zh-CN": "斐济群岛", "en-US": "Fiji", "fr-FR": "Fidji"}},
  {"code": "FI", "name": {"zh-CN": "芬兰", "en-US": "Finland", "fr-FR": "Finlande"}},
  {"code": "FR", "name": {"zh-CN": "法国", "en-US": "France", "fr-FR": "France"}},
  {"code": "GF", "name": {"zh-CN": "法属圭亚那", "en-US": "French Guiana", "fr-FR": "Guyane française"}},
  {"code": "PF", "name": {"zh-CN": "法属波利尼西亚", "en-US": "French Polynesia", "fr-FR": "Polynésie française"}},
  {
    "code": "TF",
    "name": {
      "zh-CN": "法属南半球领地",
      "en-US": "French Southern Territories",
      "fr-FR": "Territoires australes français"
    }
  },
  {"code": "GA", "name": {"zh-CN": "加蓬", "en-US": "Gabon", "fr-FR": "Gabon"}},
  {"code": "GM", "name": {"zh-CN": "冈比亚", "en-US": "Gambia", "fr-FR": "Gambie"}},
  {"code": "GE", "name": {"zh-CN": "格鲁吉亚", "en-US": "Georgia", "fr-FR": "Géorgie"}},
  {"code": "DE", "name": {"zh-CN": "德国", "en-US": "Germany", "fr-FR": "Allemagne"}},
  {"code": "GH", "name": {"zh-CN": "加纳", "en-US": "Ghana", "fr-FR": "Ghana"}},
  {"code": "GI", "name": {"zh-CN": "直布罗陀", "en-US": "Gibraltar", "fr-FR": "Gibraltar"}},
  {"code": "GR", "name": {"zh-CN": "希腊", "en-US": "Greece", "fr-FR": "Grèce"}},
  {"code": "GL", "name": {"zh-CN": "格陵兰群岛", "en-US": "Greenland", "fr-FR": "Groenland"}},
  {"code": "GD", "name": {"zh-CN": "格林纳达", "en-US": "Grenada", "fr-FR": "Grenade"}},
  {"code": "GP", "name": {"zh-CN": "瓜德罗普岛", "en-US": "Guadeloupe", "fr-FR": "Guadeloupe"}},
  {"code": "GU", "name": {"zh-CN": "关岛", "en-US": "Guam", "fr-FR": "Guam"}},
  {"code": "GT", "name": {"zh-CN": "危地马拉", "en-US": "Guatemala", "fr-FR": "Guatemala"}},
  {"code": "GN", "name": {"zh-CN": "几内亚", "en-US": "Guinea", "fr-FR": "Guinée"}},
  {"code": "GW", "name": {"zh-CN": "几内亚比绍", "en-US": "Guinea-Bissau", "fr-FR": "Guinée-Bissau"}},
  {"code": "GY", "name": {"zh-CN": "圭亚那", "en-US": "Guyana", "fr-FR": "Guyana"}},
  {"code": "HT", "name": {"zh-CN": "海地", "en-US": "Haiti", "fr-FR": "Haïti"}},
  {
    "code": "HM",
    "name": {
      "zh-CN": "赫德与麦克唐纳群岛",
      "en-US": "Heard Island and McDonald Islands",
      "fr-FR": "Îles Heard et McDonald"
    }
  },
  {"code": "VA", "name": {"zh-CN": "梵地冈", "en-US": "Vatican City", "fr-FR": "Vatican"}},
  {"code": "HN", "name": {"zh-CN": "洪都拉斯", "en-US": "Honduras", "fr-FR": "Honduras"}},
  {"code": "HK", "name": {"zh-CN": "香港(中国)", "en-US": "Hong Kong", "fr-FR": "Hong Kong"}},
  {"code": "HU", "name": {"zh-CN": "匈牙利", "en-US": "Hungary", "fr-FR": "Hongrie"}},
  {"code": "IS", "name": {"zh-CN": "冰岛", "en-US": "Iceland", "fr-FR": "Islande"}},
  {"code": "IN", "name": {"zh-CN": "印度", "en-US": "India", "fr-FR": "Inde"}},
  {"code": "ID", "name": {"zh-CN": "印度尼西亚", "en-US": "Indonesia", "fr-FR": "Indonésie"}},
  {"code": "IR", "name": {"zh-CN": "伊朗", "en-US": "Iran", "fr-FR": "Iran"}},
  {"code": "IQ", "name": {"zh-CN": "伊拉克", "en-US": "Iraq", "fr-FR": "Irak"}},
  {"code": "IE", "name": {"zh-CN": "爱尔兰", "en-US": "Ireland", "fr-FR": "Irlande"}},
  {"code": "IL", "name": {"zh-CN": "以色列", "en-US": "Israel", "fr-FR": "Israël"}},
  {"code": "IT", "name": {"zh-CN": "意大利", "en-US": "Italy", "fr-FR": "Italie"}},
  {"code": "JM", "name": {"zh-CN": "牙买加", "en-US": "Jamaica", "fr-FR": "Jamaïque"}},
  {"code": "JP", "name": {"zh-CN": "日本", "en-US": "Japan", "fr-FR": "Japon"}},
  {"code": "JO", "name": {"zh-CN": "约旦", "en-US": "Jordan", "fr-FR": "Jordanie"}},
  {"code": "KZ", "name": {"zh-CN": "哈萨克斯坦", "en-US": "Kazakhstan", "fr-FR": "Kazakhstan"}},
  {"code": "KE", "name": {"zh-CN": "肯尼亚", "en-US": "Kenya", "fr-FR": "Kenya"}},
  {"code": "KI", "name": {"zh-CN": "基里巴斯", "en-US": "Kiribati", "fr-FR": "Kiribati"}},
  {"code": "KP", "name": {"zh-CN": "朝鲜", "en-US": "North Korea", "fr-FR": "Corée du Nord"}},
  {"code": "KR", "name": {"zh-CN": "韩国", "en-US": "South Korea", "fr-FR": "Corée du Sud"}},
  {"code": "KW", "name": {"zh-CN": "科威特", "en-US": "Kuwait", "fr-FR": "Koweït"}},
  {"code": "KG", "name": {"zh-CN": "吉尔吉斯斯坦", "en-US": "Kyrgyzstan", "fr-FR": "Kirghizistan"}},
  {"code": "LA", "name": {"zh-CN": "老挝", "en-US": "Laos", "fr-FR": "Laos"}},
  {"code": "LV", "name": {"zh-CN": "拉脱维亚", "en-US": "Latvia", "fr-FR": "Lettonie"}},
  {"code": "LB", "name": {"zh-CN": "黎巴嫩", "en-US": "Lebanon", "fr-FR": "Liban"}},
  {"code": "LS", "name": {"zh-CN": "莱索托", "en-US": "Lesotho", "fr-FR": "Lesotho"}},
  {"code": "LR", "name": {"zh-CN": "利比里亚", "en-US": "Liberia", "fr-FR": "Libéria"}},
  {"code": "LY", "name": {"zh-CN": "利比亚", "en-US": "Libya", "fr-FR": "Libye"}},
  {"code": "LI", "name": {"zh-CN": "列支敦士登", "en-US": "Liechtenstein", "fr-FR": "Liechtenstein"}},
  {"code": "LT", "name": {"zh-CN": "立陶宛", "en-US": "Lithuania", "fr-FR": "Lituanie"}},
  {"code": "LU", "name": {"zh-CN": "卢森堡", "en-US": "Luxembourg", "fr-FR": "Luxembourg"}},
  {"code": "MO", "name": {"zh-CN": "澳门(中国)", "en-US": "Macao", "fr-FR": "Macao"}},
  {"code": "MG", "name": {"zh-CN": "马达加斯加", "en-US": "Madagascar", "fr-FR": "Madagascar"}},
  {"code": "MW", "name": {"zh-CN": "马拉维", "en-US": "Malawi", "fr-FR": "Malawi"}},
  {"code": "MY", "name": {"zh-CN": "马来西亚", "en-US": "Malaysia", "fr-FR": "Malaisie"}},
  {"code": "MV", "name": {"zh-CN": "马尔代夫", "en-US": "Maldives", "fr-FR": "Maldives"}},
  {"code": "ML", "name": {"zh-CN": "马里", "en-US": "Mali", "fr-FR": "Mali"}},
  {"code": "MT", "name": {"zh-CN": "马耳他", "en-US": "Malta", "fr-FR": "Malte"}},
  {"code": "MH", "name": {"zh-CN": "马绍尔群岛", "en-US": "Marshall Islands", "fr-FR": "Îles Marshall"}},
  {"code": "MQ", "name": {"zh-CN": "马提尼克岛", "en-US": "Martinique", "fr-FR": "Martinique"}},
  {"code": "MR", "name": {"zh-CN": "毛里塔尼亚", "en-US": "Mauritania", "fr-FR": "Mauritanie"}},
  {"code": "MU", "name": {"zh-CN": "毛里求斯", "en-US": "Mauritius", "fr-FR": "Maurice"}},
  {"code": "YT", "name": {"zh-CN": "马约特岛", "en-US": "Mayotte", "fr-FR": "Mayotte"}},
  {"code": "MX", "name": {"zh-CN": "墨西哥", "en-US": "Mexico", "fr-FR": "Mexique"}},
  {"code": "FM", "name": {"zh-CN": "密克罗尼西亚", "en-US": "Micronesia", "fr-FR": "Micronésie"}},
  {"code": "MD", "name": {"zh-CN": "摩尔多瓦", "en-US": "Moldova", "fr-FR": "Moldavie"}},
  {"code": "MC", "name": {"zh-CN": "摩纳哥", "en-US": "Monaco", "fr-FR": "Monaco"}},
  {"code": "MN", "name": {"zh-CN": "蒙古", "en-US": "Mongolia", "fr-FR": "Mongolie"}},
  {"code": "MS", "name": {"zh-CN": "蒙塞拉特岛", "en-US": "Montserrat", "fr-FR": "Montserrat"}},
  {"code": "MA", "name": {"zh-CN": "摩洛哥", "en-US": "Morocco", "fr-FR": "Maroc"}},
  {"code": "MZ", "name": {"zh-CN": "莫桑比克", "en-US": "Mozambique", "fr-FR": "Mozambique"}},
  {"code": "MM", "name": {"zh-CN": "缅甸", "en-US": "Myanmar", "fr-FR": "Birmanie"}},
  {"code": "NA", "name": {"zh-CN": "纳米比亚", "en-US": "Namibia", "fr-FR": "Namibie"}},
  {"code": "NR", "name": {"zh-CN": "瑙鲁", "en-US": "Nauru", "fr-FR": "Nauru"}},
  {"code": "NP", "name": {"zh-CN": "尼泊尔", "en-US": "Nepal", "fr-FR": "Népal"}},
  {"code": "NL", "name": {"zh-CN": "荷兰", "en-US": "Netherlands", "fr-FR": "Pays-Bas"}},
  {"code": "NC", "name": {"zh-CN": "新喀里多尼亚", "en-US": "New Caledonia", "fr-FR": "Nouvelle-Calédonie"}},
  {"code": "NZ", "name": {"zh-CN": "新西兰", "en-US": "New Zealand", "fr-FR": "Nouvelle-Zélande"}},
  {"code": "NI", "name": {"zh-CN": "尼加拉瓜", "en-US": "Nicaragua", "fr-FR": "Nicaragua"}},
  {"code": "NE", "name": {"zh-CN": "尼日尔", "en-US": "Niger", "fr-FR": "Niger"}},
  {"code": "NG", "name": {"zh-CN": "尼日利亚", "en-US": "Nigeria", "fr-FR": "Nigéria"}},
  {"code": "NU", "name": {"zh-CN": "纽埃岛", "en-US": "Niue", "fr-FR": "Nioué"}},
  {"code": "NF", "name": {"zh-CN": "诺福克岛", "en-US": "Norfolk Island", "fr-FR": "Île Norfolk"}},
  {"code": "MK", "name": {"zh-CN": "北马其顿", "en-US": "North Macedonia", "fr-FR": "Macédoine du Nord"}},
  {
    "code": "MP",
    "name": {"zh-CN": "北马里亚纳群岛", "en-US": "Northern Mariana Islands", "fr-FR": "Îles Mariannes du Nord"}
  },
  {"code": "NO", "name": {"zh-CN": "挪威", "en-US": "Norway", "fr-FR": "Norvège"}},
  {"code": "OM", "name": {"zh-CN": "阿曼", "en-US": "Oman", "fr-FR": "Oman"}},
  {"code": "PK", "name": {"zh-CN": "巴基斯坦", "en-US": "Pakistan", "fr-FR": "Pakistan"}},
  {"code": "PW", "name": {"zh-CN": "帕劳", "en-US": "Palau", "fr-FR": "Palaos"}},
  {"code": "PS", "name": {"zh-CN": "巴勒斯坦", "en-US": "Palestine", "fr-FR": "Palestine"}},
  {"code": "PA", "name": {"zh-CN": "巴拿马", "en-US": "Panama", "fr-FR": "Panama"}},
  {
    "code": "PG",
    "name": {"zh-CN": "巴布亚新几内亚", "en-US": "Papua New Guinea", "fr-FR": "Papouasie-Nouvelle-Guinée"}
  },
  {"code": "PY", "name": {"zh-CN": "巴拉圭", "en-US": "Paraguay", "fr-FR": "Paraguay"}},
  {"code": "PE", "name": {"zh-CN": "秘鲁", "en-US": "Peru", "fr-FR": "Pérou"}},
  {"code": "PH", "name": {"zh-CN": "菲律宾", "en-US": "Philippines", "fr-FR": "Philippines"}},
  {"code": "PN", "name": {"zh-CN": "皮特克恩岛", "en-US": "Pitcairn Islands", "fr-FR": "Îles Pitcairn"}},
  {"code": "PL", "name": {"zh-CN": "波兰", "en-US": "Poland", "fr-FR": "Pologne"}},
  {"code": "PT", "name": {"zh-CN": "葡萄牙", "en-US": "Portugal", "fr-FR": "Portugal"}},
  {"code": "PR", "name": {"zh-CN": "波多黎各", "en-US": "Puerto Rico", "fr-FR": "Porto Rico"}},
  {"code": "QA", "name": {"zh-CN": "卡塔尔", "en-US": "Qatar", "fr-FR": "Qatar"}},
  {"code": "RO", "name": {"zh-CN": "罗马尼亚", "en-US": "Romania", "fr-FR": "Roumanie"}},
  {"code": "RU", "name": {"zh-CN": "俄罗斯", "en-US": "Russia", "fr-FR": "Russie"}},
  {"code": "RW", "name": {"zh-CN": "卢旺达", "en-US": "Rwanda", "fr-FR": "Rwanda"}},
  {"code": "RE", "name": {"zh-CN": "留尼汪岛", "en-US": "Réunion", "fr-FR": "Réunion"}},
  {"code": "SH", "name": {"zh-CN": "圣赫勒拿", "en-US": "Saint Helena", "fr-FR": "Sainte-Hélène"}},
  {
    "code": "KN",
    "name": {"zh-CN": "圣基茨和尼维斯", "en-US": "Saint Kitts and Nevis", "fr-FR": "Saint-Christophe-et-Niévès"}
  },
  {"code": "LC", "name": {"zh-CN": "圣露西亚岛", "en-US": "Saint Lucia", "fr-FR": "Sainte-Lucie"}},
  {
    "code": "PM",
    "name": {"zh-CN": "圣皮埃尔和密克隆群岛", "en-US": "Saint Pierre and Miquelon", "fr-FR": "Saint-Pierre-et-Miquelon"}
  },
  {
    "code": "VC",
    "name": {
      "zh-CN": "圣文森特和格林纳丁斯",
      "en-US": "Saint Vincent and the Grenadines",
      "fr-FR": "Saint-Vincent-et-les-Grenadines"
    }
  },
  {"code": "WS", "name": {"zh-CN": "萨摩亚", "en-US": "Samoa", "fr-FR": "Samoa"}},
  {"code": "SM", "name": {"zh-CN": "圣马力诺", "en-US": "San Marino", "fr-FR": "Saint-Marin"}},
  {
    "code": "ST",
    "name": {"zh-CN": "圣多美和普林西比", "en-US": "Sao Tome and Principe", "fr-FR": "São Tomé-et-Principe"}
  },
  {"code": "SA", "name": {"zh-CN": "沙特阿拉伯", "en-US": "Saudi Arabia", "fr-FR": "Arabie saoudite"}},
  {"code": "SN", "name": {"zh-CN": "塞内加尔", "en-US": "Senegal", "fr-FR": "Sénégal"}},
  {"code": "SC", "name": {"zh-CN": "塞舌尔", "en-US": "Seychelles", "fr-FR": "Seychelles"}},
  {"code": "SL", "name": {"zh-CN": "塞拉利昂", "en-US": "Sierra Leone", "fr-FR": "Sierra Leone"}},
  {"code": "SG", "name": {"zh-CN": "新加坡", "en-US": "Singapore", "fr-FR": "Singapour"}},
  {"code": "SK", "name": {"zh-CN": "斯洛伐克", "en-US": "Slovakia", "fr-FR": "Slovaquie"}},
  {"code": "SI", "name": {"zh-CN": "斯洛文尼亚", "en-US": "Slovenia", "fr-FR": "Slovénie"}},
  {"code": "SB", "name": {"zh-CN": "所罗门群岛", "en-US": "Solomon Islands", "fr-FR": "Îles Salomon"}},
  {"code": "SO", "name": {"zh-CN": "索马里", "en-US": "Somalia", "fr-FR": "Somalie"}},
  {"code": "ZA", "name": {"zh-CN": "南非", "en-US": "South Africa", "fr-FR": "Afrique du Sud"}},
  {
    "code": "GS",
    "name": {
      "zh-CN": "南乔治亚岛和南桑德韦奇岛",
      "en-US": "South Georgia and the South Sandwich Islands",
      "fr-FR": "Géorgie du Sud et îles Sandwich du Sud"
    }
  },
  {"code": "ES", "name": {"zh-CN": "西班牙", "en-US": "Spain", "fr-FR": "Espagne"}},
  {"code": "LK", "name": {"zh-CN": "斯里兰卡", "en-US": "Sri Lanka", "fr-FR": "Sri Lanka"}},
  {"code": "SD", "name": {"zh-CN": "苏丹", "en-US": "Sudan", "fr-FR": "Soudan"}},
  {"code": "SR", "name": {"zh-CN": "苏里南", "en-US": "Suriname", "fr-FR": "Suriname"}},
  {
    "code": "SJ",
    "name": {"zh-CN": "斯瓦尔巴特和扬马延岛", "en-US": "Svalbard and Jan Mayen", "fr-FR": "Svalbard et Jan Mayen"}
  },
  {"code": "SE", "name": {"zh-CN": "瑞典", "en-US": "Sweden", "fr-FR": "Suède"}},
  {"code": "CH", "name": {"zh-CN": "瑞士", "en-US": "Switzerland", "fr-FR": "Suisse"}},
  {"code": "SY", "name": {"zh-CN": "叙利亚", "en-US": "Syria", "fr-FR": "Syrie"}},
  {"code": "TW", "name": {"zh-CN": "台湾(中国)", "en-US": "Taiwan", "fr-FR": "Taïwan"}},
  {"code": "TJ", "name": {"zh-CN": "塔吉克斯坦", "en-US": "Tajikistan", "fr-FR": "Tadjikistan"}},
  {"code": "TZ", "name": {"zh-CN": "坦桑尼亚", "en-US": "Tanzania", "fr-FR": "Tanzanie"}},
  {"code": "TH", "name": {"zh-CN": "泰国", "en-US": "Thailand", "fr-FR": "Thaïlande"}},
  {"code": "TL", "name": {"zh-CN": "东帝汶", "en-US": "Timor-Leste", "fr-FR": "Timor-Leste"}},
  {"code": "TG", "name": {"zh-CN": "多哥", "en-US": "Togo", "fr-FR": "Togo"}},
  {"code": "TK", "name": {"zh-CN": "托克劳群岛", "en-US": "Tokelau", "fr-FR": "Tokélaou"}},
  {"code": "TO", "name": {"zh-CN": "汤加", "en-US": "Tonga", "fr-FR": "Tonga"}},
  {"code": "TT", "name": {"zh-CN": "特立尼达和多巴哥", "en-US": "Trinidad and Tobago", "fr-FR": "Trinité-et-Tobago"}},
  {"code": "TN", "name": {"zh-CN": "突尼斯", "en-US": "Tunisia", "fr-FR": "Tunisie"}},
  {"code": "TM", "name": {"zh-CN": "土库曼斯坦", "en-US": "Turkmenistan", "fr-FR": "Turkménistan"}},
  {
    "code": "TC",
    "name": {"zh-CN": "特克斯和凯科斯群岛", "en-US": "Turks and Caicos Islands", "fr-FR": "Îles Turks et Caïques"}
  },
  {"code": "TV", "name": {"zh-CN": "图瓦鲁", "en-US": "Tuvalu", "fr-FR": "Tuvalu"}},
  {"code": "TR", "name": {"zh-CN": "土耳其", "en-US": "Turkey", "fr-FR": "Turquie"}},
  {"code": "UG", "name": {"zh-CN": "乌干达", "en-US": "Uganda", "fr-FR": "Ouganda"}},
  {"code": "UA", "name": {"zh-CN": "乌克兰", "en-US": "Ukraine", "fr-FR": "Ukraine"}},
  {"code": "AE", "name": {"zh-CN": "阿联酋", "en-US": "United Arab Emirates", "fr-FR": "Émirats arabes unis"}},
  {"code": "GB", "name": {"zh-CN": "英国", "en-US": "United Kingdom", "fr-FR": "Royaume-Uni"}},
  {
    "code": "UM",
    "name": {
      "zh-CN": "美国本土外小岛屿",
      "en-US": "United States Minor Outlying Islands",
      "fr-FR": "Îles mineures éloignées des États-Unis"
    }
  },
  {"code": "US", "name": {"zh-CN": "美国", "en-US": "United States", "fr-FR": "États-Unis"}},
  {"code": "UY", "name": {"zh-CN": "乌拉圭", "en-US": "Uruguay", "fr-FR": "Uruguay"}},
  {"code": "UZ", "name": {"zh-CN": "乌兹别克斯坦", "en-US": "Uzbekistan", "fr-FR": "Ouzbékistan"}},
  {"code": "VU", "name": {"zh-CN": "瓦努阿图", "en-US": "Vanuatu", "fr-FR": "Vanuatu"}},
  {"code": "VE", "name": {"zh-CN": "委内瑞拉", "en-US": "Venezuela", "fr-FR": "Venezuela"}},
  {"code": "VN", "name": {"zh-CN": "越南", "en-US": "Vietnam", "fr-FR": "Vietnam"}},
  {
    "code": "VG",
    "name": {"zh-CN": "维尔京群岛", "en-US": "Virgin Islands (British)", "fr-FR": "Îles Vierges britanniques"}
  },
  {
    "code": "VI",
    "name": {"zh-CN": "美属维京群岛", "en-US": "Virgin Islands (US)", "fr-FR": "Îles Vierges américaines"}
  },
  {"code": "WF", "name": {"zh-CN": "瓦利斯和富图钠群岛", "en-US": "Wallis and Futuna", "fr-FR": "Wallis-et-Futuna"}},
  {"code": "EH", "name": {"zh-CN": "西撒哈拉", "en-US": "Western Sahara", "fr-FR": "Sahara occidental"}},
  {"code": "YE", "name": {"zh-CN": "也门", "en-US": "Yemen", "fr-FR": "Yémen"}},
  {"code": "ZM", "name": {"zh-CN": "赞比亚", "en-US": "Zambia", "fr-FR": "Zambie"}},
  {"code": "ZW", "name": {"zh-CN": "津巴布韦", "en-US": "Zimbabwe", "fr-FR": "Zimbabwe"}}
];